s = set()
n = int(input("Enter the number of elements you want to add in the set: "))
s.add(n)
n = int(input("Enter the number of elements you want to add in the set: "))
s.add(n)
n = int(input("Enter the number of elements you want to add in the set: "))
s.add(n)
n = int(input("Enter the number of elements you want to add in the set: "))
s.add(n)
n = int(input("Enter the number of elements you want to add in the set: "))
s.add(n)
n = int(input("Enter the number of elements you want to add in the set: "))
s.add(n)
n = int(input("Enter the number of elements you want to add in the set: "))
s.add(n)
n = int(input("Enter the number of elements you want to add in the set: "))
s.add(n)
print(s)