d = {}
name = input("Enter your name: ")
lang = input("Enter you faviourite programming Language : ")
d.update({name : lang})
name = input("Enter your name: ")
lang = input("Enter you faviourite programming Language : ")
d.update({name : lang})
name = input("Enter your name: ")
lang = input("Enter you faviourite programming Language : ")
d.update({name : lang})
name = input("Enter your name: ")
lang = input("Enter you faviourite programming Language : ")
d.update({name : lang})
print(d)